*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Juputer Notebook.

Use the JupyterHub server on the Google Cloud Platform, provided by your designated instructor, for this assignment. Ensure using Python 3.7.6 release then complete the assignment by inserting your Python code wherever seeing the string "#INSERT YOUR ANSWER HERE."

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1 


**a)** Define a function called `isSymmetrical` that takes a string value as a parameter and returns `TRUE` if the given string is Symmetrical. A string is said to be symmetrical if the reverse of the string is the same as string. For example, “madam” is symmetrical, but “water” is not symmetrical.

In [7]:
def isSymmetrical(word): 

      answer=""
      if(len(word)>1):
       newWords = word[::-1] 
       if(word == newWords):
          answer= "True"
       else:
          answer="False"

      return answer

str = input("Enter the string to check :")
isSymmetrical(str)


Enter the string to check : madam


'True'

**b)** *Modify the `isSymmetrical` function you created in Q1.a to take any type of data as an input and return `TRUE` if the input is symmetrical. For example, "12321" is symmetrical, but "12345" is not symmetrical.

In [6]:
def isSymmetrical(word): 
      answer=""
      newWords = word[::-1] 
      if(word == newWords):
          answer= "True"
      else:
          answer="False"

      return answer


def reverseWord(Str): 
  
    # Splitting the Sentence into list of words. 
   words = Str.split(" ") 
   answers=""  
    # Reversing each word and creating 
    # a new list of words 
    # List Comprehension Technique 
   for word in words:
        if(len(word)>1):
            if( "True" == isSymmetrical(word)):
              print("True")
            elif("False" == isSymmetrical(word)):
               print("False")
        


st = input("Enter the string to check :")
reverseWord(st)

Enter the string to check : 12345


False


**c)** Define a function called `isSymmetricalVec` that calls `isSymmetrical` function you updated in Q1.b to take a list of elements and return their results in a list.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns \[`TRUE`, `FALSE`, `TRUE`, `TRUE`, `FALSE`\]

In [8]:
def isSymmetrical(word): 
      answer=""
      newWords = word[::-1] 
      if(word == newWords):
          answer= "True"
      else:
          answer="False"

      return answer

def isSymmetricalVec(Str): 
  
    # Splitting the Sentence into list of words. 
 
 list1=list(Str.split(" ")) 
 list2=[]

 
     # Reversing each word and creating 
    # a new list of words 
    # List Comprehension Technique 
 for index in range(len(list1)):
   if(len(list1[index])>1):
     if("True" == isSymmetrical(list1[index])):
           list2.append("True")
    
     elif("False" == isSymmetrical(list1[index])):
         list2.append("False")
  

 return list2 

st = input("Enter the string to check :")
isSymmetricalVec(st)



Enter the string to check : 1441 Apple radar 232 plane


['True', 'False', 'True', 'True', 'False']

**d)**  Define a function called `isSymmetricalDict` by modifying the function you created in Q1.c to return the results in a dictionary with their corresponding input elements. \
For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns {"1441": `TRUE`, "Apple": `FALSE`, "radar": `TRUE`, "232": `TRUE`, "plane": `FALSE`\}

In [9]:
def isSymmetrical(word): 
      answer=""
      newWords = word[::-1] 
      if(word == newWords):
          answer= "True"
      else:
          answer="False"

      return answer

def  isSymmetricalDict(Str): 
  
    # Splitting the Sentence into list of words. 
 
 list1=list(Str.split(" ")) 
 sample_dictionary={}

 
     # Reversing each word and creating 
    # a new list of words 
    # List Comprehension Technique 
 for index in range(len(list1)):
   if(len(list1[index])>1):
     if("True" == isSymmetrical(list1[index])):
           sample_dictionary[list1[index]]= True
    
     elif("False" == isSymmetrical(list1[index])):
         sample_dictionary[list1[index]]= False
  
 return sample_dictionary

st = input("Enter the string to check :")
isSymmetricalDict(st)

Enter the string to check : 1441 Apple radar 232 plane 


{'1441': True, 'Apple': False, 'radar': True, '232': True, 'plane': False}

**e)** Define a function called `isSymmetricalTuple` by modifying the function you created in Q1.d to traverse the values of the returned dictionary **in reverse order** and return the dictionary keys that has a **`TRUE`** value as a tuple.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns ("232", "radar","1441").

In [3]:
def isSymmetrical(word): 
      answer=""
      newWords = word[::-1] 
      if(word == newWords):
          answer= "True"
      else:
          answer="False"

      return answer

def  isSymmetricalDict(Str): 
  
    # Splitting the Sentence into list of words. 
 
 list1=list(Str.split(" ")) 
 sample_dictionary={}

 
     # Reversing each word and creating 
    # a new list of words 
    # List Comprehension Technique 
 for index in range(len(list1)):
   if(len(list1[index])>1):
     if("True" == isSymmetrical(list1[index])):
           sample_dictionary[list1[index]]= True
    
     elif("False" == isSymmetrical(list1[index])):
         sample_dictionary[list1[index]]= False
  
 return sample_dictionary

def isSymmetricalTuple(my_string):

    
    sample_dic = isSymmetricalDict(my_string)
       
  
    listofkey= [key  for (key, value) in sample_dic.items() if value == True]
    return tuple(reversed(listofkey))
    

str = input("Enter the string to check :")
isSymmetricalTuple(str)




Enter the string to check :1441  Apple  radar 232  plane


('232', 'radar', '1441')

*****



### Question 2




**a)**Define a function called `minSubStr` that takes two string arguments ( S and T ), and returns `TRUE` if the characters of *T* exist in *S*, else returns `FALSE`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns `TRUE` (`T = "ABCD"`, returns `FALSE)`


In [3]:
def minSubStr(x,y):
  S=x
  T=y
  answer=""
  count=0
  index=0
  while index < len(T):
     letter = T[index]
     #print(letter)
     index+=1
     if  letter in S:
        count+=1
        if count== len(T):
         answer ="True"
     else:
       answer ="False "

  return answer

minSubStr("xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx", "ABC")  

'True'

**b)** Modify your `minSubStr` function defined in Q2.a to return the first possible substring (traversing from left) containing all the elements of `T`. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"BxxAxxC"`**

In [2]:
def minSubStr(x,y):
  S=x
  T=y
  num =[]
  count=0
  index=0
  while index < len(S):
    letter = S[index]
    index+=1
    if  letter in T:
        letterindex = index-1
        count+=1
        num.append(letterindex)
        if count== len(T):
          num1=int(num[0])
          numlast= int(num[-1])+1
          answer =S[num1:numlast]
          
  return answer




minSubStr("xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx", "ABC")      
    

'BxxAxxC'

**c)**  Modify your `minSubStr` function defined in Q2.b to return the shortest substring containing all the elements of T. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxCxB"`**


In [2]:
 ''''def minSubStr(x,y):
  S=x
  T=y
  num =[]
  count=0
  index=0
  listlen = 0
  answer=""
  while index < len(S):
    letter = S[index]
    index+=1
    
    if  letter in T:
        letterindex=index-1
       # print(letterindex)
        count+=1
        num.append(letterindex)
        if count == len(T):
          num1= int(num[0])
          numlast=int(num[-1]) +1
          subset = S[num1:numlast]
         # print(subset , len(subset))
          if listlen == 0:
           listlen =len(subset)
           answer= subset
          if listlen > len(subset) :
            listlen= len(subset)
            answer= subset
          count= 0
          num=[]  
        
    
  return answer
     

minSubStr("xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx", "ABC")'''
    
# Python3 program to find the smallest window
# containing all characters of a pattern.
no_of_chars = 256
 
# Function to find smallest window
# containing all characters of 'pat'
def findSubString(string, pat):
 
    len1 = len(string)
    len2 = len(pat)
 
    # Check if string's length is
    # less than pattern's
    # length. If yes then no such
    # window can exist
    if len1 < len2:
 
        print("False")
        return ""
 
    hash_pat = [0] * no_of_chars
    hash_str = [0] * no_of_chars
 
    # Store occurrence ofs characters of pattern
    for i in range(0, len2):
        hash_pat[ord(pat[i])] += 1
 
    start, start_index, min_len = 0, -1, float('inf')
 
    # Start traversing the string
    count = 0  # count of characters
    for j in range(0, len1):
 
        # count occurrence of characters of string
        hash_str[ord(string[j])] += 1
 
        # If string's char matches with
        # pattern's char then increment count
        if (hash_str[ord(string[j])] <=
                hash_pat[ord(string[j])]):
            count += 1
 
        # if all the characters are matched
        if count == len2:
 
            # Try to minimize the window
            while (hash_str[ord(string[start])] >
                   hash_pat[ord(string[start])] or
                   hash_pat[ord(string[start])] == 0):
 
                if (hash_str[ord(string[start])] >
                        hash_pat[ord(string[start])]):
                    hash_str[ord(string[start])] -= 1
                start += 1
 


            # update window size
            len_window = j - start + 1
            if min_len > len_window:
              
                min_len = len_window
                start_index = start
 
    # If no window found
    if start_index == -1:
        print("False")
        return ""
 
    # Return substring starting from
    # start_index and length min_len
    return string[start_index: start_index + min_len]


findSubString("xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx", "ABC")  

'AxCxB'

**d)**  modify your `minSubStr` function defined in Q2.c to return the shortest substring containing all the elements of T in order. For example: given `S = 'xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx'` and `T = "ABC"`, returns **`"AxxBxC"`**

In [1]:
def minWindow( S, T):
        """
        :type S: str
        :type T: str
        :rtype: str
        dp[i][j]: the start position of Minimum Window Subsequence for S[:i] and T[:j]
        """
        m = len(S)
        n = len(T)
        dp = [[-1 for j in range(n+1)] for i in range(m+1)]
        
        for i in range(m+1):
            dp[i][0] = i
        length = float('inf')
        print("False")
        ans = ""
        
        for i in range(1, m+1):
            for j in range(1, n+1):
                if S[i-1] == T[j-1]:
                    dp[i][j] = dp[i-1][j-1]
                else:
                    dp[i][j] = dp[i-1][j]
                if dp[i][n] != -1 and i - dp[i][n] < length:
                    length = i - dp[i][n]
                    ans = S[dp[i][n]:i]
        return ans

minWindow("xBxxAxxCxxAxCxxBxxxAxCxBxxxAxxBxCx", "ABC")    

'AxxBxC'

*****

### Question 3 


In [10]:

#INSERT YOUR ANSWER HERE.
# Define Shape class
class Shape:
    count = 0

    def __init__(self):
        #general init stuff
        self.inc_count()

    def inc_count(self):
        Shape.count += 1
     #   super().inc_count() #removing this avoids AttributeError but means having
                            # unique methods for inc_count in all SubCls level Classes


   

# Define Oval class
class Oval(Shape):
    
    count = 0

    def __init__(self):
        super().__init__()
        #unique init stuff

    def inc_count(self):
        Oval.count += 1
        super().inc_count()

    
# Define Circle class
class Circle(Shape):
    
    count = 0

    def __init__(self):
        super().__init__()
        #unique init stuf

    def inc_count(self):
        Circle.count += 1
        super().inc_count()


# Run the following lines of code 

from random import choice
list_of_shapes = [choice(['Circle', 'Oval']) for x in range(10)]
for shape in list_of_shapes:
  if shape == 'Oval':
    # create an object of oval
    answer=Oval()
  else:
    # create an object of circle class
    answer1= Circle()


# Print the list_of_shapes
print(list_of_shapes)
# Print number of shape objects
print("There are ", Shape.count ," random shape objects.")
# Print number of Oval objects
print(Oval.count , "of them are oval")
# Print number of circle objects
print(Circle.count ,"of them are Circle")
# Run the following lines of code 



['Oval', 'Circle', 'Circle', 'Circle', 'Circle', 'Oval', 'Oval', 'Circle', 'Circle', 'Circle']
There are  10  random shape objects.
3 of them are oval
7 of them are Circle


#### This is the end of assignment 2